{
    "swagger": "2.0",
    "info": {
        "title": "UnityWiFi API",
        "description": "API for managing users, hotspots, and data usage for the UnityWiFi platform.",
        "version": "1.0.0"
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header",
            "description": "JWT Bearer token required, e.g., 'Bearer eyJhbGci...'"
        }
    },
    "definitions": {
        "UserSchema": {
            "type": "object",
            "required": ["username", "email", "password"],
            "properties": {
                "username": {
                    "type": "string",
                    "minLength": 1,
                    "maxLength": 255,
                    "description": "User's username."
                },
                "email": {
                    "type": "string",
                    "format": "email",
                    "minLength": 1,
                    "maxLength": 255,
                    "description": "User's email address."
                },
                "password": {
                    "type": "string",
                    "minLength": 8,
                    "description": "User's password (minimum 8 characters)."
                }
            }
        },
        "HotspotSchema": {
            "type": "object",
            "required": ["ssid", "bssid", "latitude", "longitude", "encryption_method"],
            "properties": {
                "ssid": {
                    "type": "string",
                    "minLength": 1,
                    "maxLength": 255,
                    "description": "SSID of the hotspot."
                },
                "bssid": {
                    "type": "string",
                    "pattern": "^([0-9A-Fa-f]{2}:){5}([0-9A-Fa-f]{2})$",
                    "description": "BSSID of the hotspot (MAC address)."
                },
                "latitude": {
                    "type": "number",
                    "format": "float",
                    "description": "Latitude of the location"
                },
                "longitude" : {
                    "type": "number",
                    "format": "float",
                    "description": "Longitude of the location"
                },
                "network_id": {
                    "type": "integer",
                    "minimum": 1,
                    "description": "ID of the network."
                },
                 "provider_id": {
                    "type": "integer",
                    "minimum": 1,
                    "description": "ID of the provider (organization).",
                    "nullable": True
                }
            }
        },
        "DataUsageSchema": {
            "type": "object",
            "required": ["user_id", "hotspot_id", "data_used"],
            "properties": {
                "user_id": {
                    "type": "integer",
                    "minimum": 1,
                    "description": "ID of the user."
                },
                "hotspot_id": {
                    "type": "integer",
                    "minimum": 1,
                    "description": "ID of the hotspot."
                },
                "data_used": {
                    "type": "number",
                    "format": "float",
                    "minimum": 0,
                    "description": "Data used in MB."
                }
            }
        },
        "OrganizationsSchema": {
            "type": "object",
            "required": ["provider_name", "contact_email", "contact_phone"],
            "properties": {
                "provider_name": {
                    "type": "string",
                    "minLength": 1,
                    "maxLength": 255,
                    "description": "Name of the entity providing UnityWiFi with Access Points."
                },
                "contact_email": {
                    "type": "string",
                    "description": "Email of the provider."
                },
                "contact_phone": {
                    "type": "string",
                    "maxLength": 20,
                    "description": "Phone number for the provider."
                }
            }
        },
        "ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "object",
                    "properties": {
                        "message": {
                            "type": "string",
                            "description": "Error message."
                        },
                        "code": {
                            "type": "integer",
                            "description": "HTTP status code."
                        }
                    },
                    "required": ["message", "code"]
                }
            },
            "required": ["error"]
        }
    }
}